### ISSUE TITLE
./build.sh: line 86: pushd: bin/ar71xx/: No such file or directory

### ISSUE THREAD

**Issue by ghost** [attila-lendvai/openwrt-auto-extroot#11]
Tried with lede-imagebuilder-17.01.2 and 01,same result all time.
TP-Link TL-MR3420 v2 
these packages disabled
#PREINSTALLED_PACKAGES+=" ppp ppp-mod-pppoe ppp-mod-pppol2tp ppp-mod-pptp kmod-ppp kmod-pppoe"
#PREINSTALLED_PACKAGES+=" luci"

**Comment by attila-lendvai** [comment]
probably/maybe lede changed the output dir name or structure? i would have noticed that, though... so i don't know and no time right now to look.

pull requests are welcome! ;)

otherwise i'll look eventually.

**Comment by attila-lendvai** [comment]
ok, i took another look: i had a pending commit that i forgot to push, but now it's pushed.

note that that error is not important, it just sets up a symlink for convenience if/when you are building a non-release lede (and therefore you need to use your own set of packages, which is rarely the case).
