### ISSUE TITLE
Device not mounted after sysupgrade (UUID mismatch)

### ISSUE THREAD

**Issue by pc-coholic** [attila-lendvai/openwrt-auto-extroot#12]
After upgrading from 17.01.1 to 17.01.4 (extroot to extroot), there was an issue: The overlay was not properly mounted.

Kernel will log something like `[   11.680000] block: extroot: UUID mismatch (root: 57a0acc6-ecc0a5e7-2ea71070-845539a7, overlay: d578bcbf-510a3603-823f14c1-4e16d34e)`

[This](https://forum.lede-project.org/t/solved-sd-card-extroot-stop-auto-mount-after-firmware-upgrade/4310) takes a look at what might be the underlying issue - I ended fixing the issue by mounting the USB-stick and deleting /etc/.extroot-uuid as explained [here](https://lede-project.org/docs/user-guide/extroot_configuration#troubleshooting).

Perhaps there is a way this could be automated in the future...

Another issue I ran into after the sysupgrade was, that I couldn't install any packages, as they were expecting a newer kernel. I could only solve this issue by manually `wget`ing the current kernel-ipkg and installing it. Perhaps also something that should be considered by the provisioning-script when performing a sysupgrade...

**Comment by attila-lendvai** [comment]
thanks for recording the issue!

so, the `/etc/.extroot-uuid` thing is a safety measure to avoid confusing overlays over extroots (it's the UUID of the firmware's root partition, recorded on the overlay at creation time). (the log message is very confusing, though)

would it be wise to automatically delete it in case of a mismatch? what else could we do if not that? create a FAQ or some kind of doc entry about upgrades?

unfortunately i won't have much hacking stamina to look into this now, but patches are welcome!

**Comment by arrmo** [comment]
Hi,

Perhaps a dumb question, but ... why not do this automatically? I admit, I'm having to manually do this and reboot every upgrade - it is a pain. And if extroot is enabled (in /etc/fstab), why not do this?

Thanks!

**Comment by attila-lendvai** [comment]
to be honest, i never played with openwrt upgrades, and i think this^ above is a vanilla openwrt issue, right? i mean, is there something we could do besides reporting a feature request to the openwrt guys?

**Comment by arrmo** [comment]
Yes, agreed - just not sure how to make that request. But it seems that an upgrade shouldn't break Extroot, agreed?

Thanks!

**Comment by rmandrad** [comment]
fix this feature it is annoying to remove .extroot-uuid all the time and in particular as I do a new build every week from the master

**Comment by attila-lendvai** [comment]
this is an openwrt issue, unrelated to this project, so i'll close this one. if you want to pursue it then report in the openwrt issue tracker.

the openwrt wiki suggests that it's not supported: http://wiki.openwrt.org/doc/howto/extroot#old.notes

and here's a description on how to fix manually if you nevertheless attempt an upgrade: https://wiki.mbirth.de/know-how/software/openwrt/sysupgrade-with-extroot.html
