### ISSUE TITLE
Support for 18.06.0?

### ISSUE THREAD

**Issue by clarkewd** [attila-lendvai/openwrt-auto-extroot#16]
I cloned the repository, edited the `build.sh` to have `RELEASE="18.06.0"` and then run:

    ./build.sh ar71xx generic tl-wdr3600-v1

But I get this error:

    ./build.sh: line 84: pushd: /home/user/openwrt-auto-extroot-2018-07/build/lede-imagebuilder-18.06.0-ar71xx-generic.Linux-x86_64: No such file or directory

Does `openwrt-auto-extroot` work with `18.06.0` ?

**Comment by juppin** [comment]
You have to edit also IMGBUILDER_NAME in build.sh to cope withe the namining for the new release...
It isn't called lede anymore.

Check out the release download page for the new naming...

**Comment by clarkewd** [comment]
thanks
