### ISSUE TITLE
how to change to disk layout ?

### ISSUE THREAD

**Issue by changchichung** [attila-lendvai/openwrt-auto-extroot#18]
thanks for this wonderful application.
I use this to build my own 19.07.3 openwrt image , it's perfect !

now it's 512M in / , and remain space goes to /mnt/data
like I want more space in root , like 8G or more 
can I just modify autoprovision-stage1.sh to make my own disk layout
or is there any other script should bt modified ?

**Comment by attila-lendvai** [comment]
i'm glad it is helping you!

you can just edit the shell script locally that sets up the partitions:

https://github.com/attila-lendvai/openwrt-auto-extroot/blob/master/image-extras/common/root/autoprovision-stage1.sh#L42

adding a more sophisticated support than simply locally editing the files seems to be too much trouble.

there shouldn't be any other place that needs modification.

**Comment by changchichung** [comment]
thanks !  but is this repository  not in maintenance ?

**Comment by attila-lendvai** [comment]
that depends on how you define 'being maintained'. patches are welcome and i answer issues, but i only touch/update the code when i need to set up a new router (or i get paid for it... ;)

shell script, the language, is an abomination, and as such i try to stay away from them. that doesn't help much either... :)

so, it all depends on how you look at it.
