### ISSUE TITLE
How to reset / firstboot / jffs2reset?

### ISSUE THREAD

**Issue by clarkewd** [attila-lendvai/openwrt-auto-extroot#19]
I've tried the methods on the [Failsafe Mode, Factory Reset, and Recovery Mode](https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset) page without luck.

Both the soft reset `firstboot && reboot now` and the hard reset `umount /overlay && jffs2reset && reboot now` don't seem to have any effect.

How can I reset the extroot to factory / defaults?

**Comment by attila-lendvai** [comment]
just ruin the partition table one way or another.

e.g.: `dd if=/dev/zero of=/dev/[your pendrive storage device path] bs=1M count=1`

be careful if there are other storage devices connected!

**Comment by clarkewd** [comment]
great thanks so much!
