### ISSUE TITLE
This could be added to the official OpenWrt project github, couldn't it?

### ISSUE THREAD

**Issue by q2dg** [attila-lendvai/openwrt-auto-extroot#2]
It's an very useful addon!!
I'd ask for it.
Thanks!

**Comment by attila-lendvai** [comment]
i personally wouldn't mind... but as a what? it's a high potential for confusion.

so, i doubt the openwrt maintainers would welcome it as part of openwrt.

but if you want try to ask them. their organization is rather low-tech... the mailing list flooded with patch emails, etc...

**Comment by bobafetthotmail** [comment]
@q2dg Well, the easy way is just make a pull request on their packages github repo where you add this, and see how it goes.

Anyone can do so, and imho, there is plenty of really weird, broken-ish and/or complex packages in their repos already, I don't think they will mind. Or even notice, lol.

**Comment by attila-lendvai** [comment]
the problem is that it's not yet another openwrt package, but a project that **uses** openwrt...

**Comment by CristianVladescu** [comment]
Well, it could be added to the list of pre-build images on their repo (no idea how that is done) .. but the autoprovision scripts would have to be adapted for sooo many models ...

**Comment by q2dg** [comment]
Thanks a lot

I've written the same idea in official forum (https://forum.openwrt.org/viewtopic.php?pid=315086#p315086). Maybe someone will say something "authoritative" there.

If you want to close this "issue", it will be all right.

**Comment by attila-lendvai** [comment]
ok, we'll see.
