### ISSUE TITLE
Suppport for WD My Net n750 LEDs

### ISSUE THREAD

**Issue by ShapeShifter499** [attila-lendvai/openwrt-auto-extroot#22]
I have OpenWRT already running on a WD My Net n750 but it is an older build, 19.07.9.  Due to a issue with newer builds and a possible solution of using extroot to get around it. I would like to use this to build a extroot enabled OpenWRT image. 

I know the LEDs are named differently for this model but I'm not sure where to get the proper names. The only names I see so far are: 
```
ls /sys/class/leds/
ath9k-phy0                ath9k-phy1                mynet-n750:blue:internet  mynet-n750:blue:power     mynet-n750:blue:wireless  mynet-n750:blue:wps
```

Does that mean I would insert something like the following into the `autoprovision-functions.sh` file?

```
    *mynet-n750*)
        autoprovisionUSBLed="blue:wps"
        autoprovisionStatusLed="blue:wireless"
        ;;
```

**Comment by ShapeShifter499** [comment]
I ran it anyways, didn't even really need LED status since my USB thumb drive of choice has one built in.  Was able to generate a working image. Seems to solve the issue experienced here: https://github.com/openwrt/openwrt/issues/9085 by completely skipping use of the on-board storage.  Thank you for this helpful script.

**Comment by attila-lendvai** [comment]
it looks reasonable at a first glance. you may want to open a PR with this change to benefit others.

but i'm glat you had success with it even without the help of the leds!
