### ISSUE TITLE
USB formats on reboot

### ISSUE THREAD

**Issue by mburlic** [attila-lendvai/openwrt-auto-extroot#27]
Hi,

I've created image for Asus RT-AC88U. Everything worked until one random reboot and USB that I use for extroot got formatted again. And it happened again randomly after poweroff/reboot. Not sure why this happens. I can provide more information if you direct me to what you need.

OpenWrt 23.05.2

tnx

**Comment by attila-lendvai** [comment]
oh, that's too bad! i hope you didn't lose much data!

my first idea: did you use extroot on that router and firmware version before you tried this project? did it work reliably?

maybe the storage does not reliably come online fast enough at boot, and when it fails to mount, then the auto-extroot script proceeds to format it.

the current mechanism: when the extroot is successfully mounted, then the scripts that would format the storage for extroot are hidden by it. if this mount fails, then they are executed, and the storage is formatted.

**Comment by attila-lendvai** [comment]
also, is it predictable? i.e. does it happen at every reboot, or only every non-normal reboot when you cut the power or the router crashes? or does it happen unpredictably?

**Comment by mburlic** [comment]
> oh, that's too bad! i hope you didn't lose much data!

no worries, I had a backup.

> 
> my first idea: did you use extroot on that router and firmware version before you tried this project? did it work reliably?
> 
Yes it worked great. I think that once I had a problem that USB did not mount. A reboot fixed the issue.

> maybe the storage does not reliably come online fast enough at boot, and when it fails to mount, then the auto-extroot script proceeds to format it.
> 
That was my first thought also.

> the current mechanism: when the extroot is successfully mounted, then the scripts that would format the storage for extroot are hidden by it. if this mount fails, then they are executed, and the storage is formatted.

That seems to be the issue for me. Any way for me to prevent it?



> also, is it predictable? i.e. does it happen at every reboot, or only every non-normal reboot when you cut the power or the router crashes? or does it happen unpredictably?

No it doesn't happen at every boot. First time it happened when I did a poweroff from terminal. Second two times last night when we had a power outage. Few minutes ago it booted just fine.

**Comment by attila-lendvai** [comment]
there are two options here:

1. if you want a quick solution: let it set up the extroot, and then boot up the device without the pendrive inserted, and then edit `/etc/rc.local`, and comment out the `/root/autoprovision-stage1.sh` line.

2. if you want to help improving the project for others too, then we should come up with a way to avoid this happening.

a quick idea is to include at the end of the stage1 script to do 1. automatically before it's rebooting the router. that way the firmware will be a one-shot gun that needs to be manually cocked again when a reformat of the extroot is desired (it wasn't needed much in my past use). i'm not sure what i think about this, but it does sound like a better behavior than unexpectedly reformatting the extroot in case of some delays/errors.

more data safety at the cost of a little inconvenience when a reformat is desirable.

**Comment by mburlic** [comment]
> there are two options here:
> 
> 1. if you want a quick solution: let it set up the extroot, and then boot up the device without the pendrive inserted, and then edit `/etc/rc.local`, and comment out the `/root/autoprovision-stage1.sh` line.

cool. thank you.

> 2. if you want to help improving the project for others too, then we should come up with a way to avoid this happening.
> 
that would be nice
> a quick idea is to include at the end of the stage1 script to do 1. automatically before it's rebooting the router. that way the firmware will be a one-shot gun that needs to be manually cocked again when a reformat of the extroot is desired (it wasn't needed much in my past use). i'm not sure what i think about this, but it does sound like a better behavior than unexpectedly reformatting the extroot in case of some delays/errors.
> 
I like this behavior better. I actually thought that this is done automatically and that script didn't finish. I didn't have time to review the scripts.

> more data safety at the cost of a little inconvenience when a reformat is desirable.

Hm. don't see anything wrong with manually setting that format is desirable action .
It's your call. I'm quite happy with first mitigation.

**Comment by attila-lendvai** [comment]
@mburlic i've pushed an untested attempt at fixing this. it would be nice if you could test it before you find a fix for your underlying issue...

...which ideally should be fixed, too.

**Comment by attila-lendvai** [comment]
it's worth noting here that there's already an issue opened for an alternative way of addressing this: https://github.com/attila-lendvai/openwrt-auto-extroot/issues/9

**Comment by mburlic** [comment]
ok. thank you. I just don't have time right now for testing.

**Comment by mburlic** [comment]
Ok, managed to find some time. I build new image.  It seams that issues is now gone. The only thing that is different now is that /mnt/data and swap are not mounted on boot. not a biggie for me.

**Comment by attila-lendvai** [comment]
> The only thing that is different now is that /mnt/data and swap are not mounted on boot. not a biggie for me.

...and meanwhile the extroot is mounted?

i have no hypothesis how/why that would happen.

if extroot is also not mounted, then it of course would mean that probably the pendrive didn't come up fast enough.

but if extroot works while data and swap is not mounted, then i have no clue.

all i do in the commit is that i overwrite the `/etc/rc.local` as a final step to disable our `autoprovision-stage1.sh`, but rc.local shouldn't contain anything else than our own stuff.

**Comment by mburlic** [comment]
> > The only thing that is different now is that /mnt/data and swap are not mounted on boot. not a biggie for me.
> 
> ...and meanwhile the extroot is mounted?

yes
> 
> i have no hypothesis how/why that would happen.
> 
who know. fstab only contains mount entry for extroot. I will flash it once more just to see if this will happen again

> if extroot is also not mounted, then it of course would mean that probably the pendrive didn't come up fast enough.
> 
This happens sometimes, and that was the reason that drive got formated on reboots/powerons.
> but if extroot works while data and swap is not mounted, then i have no clue.
> 
> all i do in the commit is that i overwrite the `/etc/rc.local` as a final step to disable our `autoprovision-stage1.sh`, but rc.local shouldn't contain anything else than our own stuff.
I see that. No unexpected formats. Last night I did a power cycle for test. When rebooting form luci, 5 times no problems. But did a poweroff from terminal. Had to do at least 5-6 power cycles with power button to get extroot mounted for router to boot. This has nothing to do with your scripts, just sharing my experience.

Thank you

**Comment by attila-lendvai** [comment]
FTR, this is the situation on my pre-commit setup:

```
~# cat /etc/fstab 
# <file system> <mount point> <type> <options> <dump> <pass>

~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 5.0M      5.0M         0 100% /rom
tmpfs                    59.6M    240.0K     59.4M   0% /tmp
/dev/sda2               487.2M     24.9M    426.4M   6% /overlay
overlayfs:/overlay      487.2M     24.9M    426.4M   6% /
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/sda3                 1.3G    360.0K      1.2G   0% /mnt/data

~# cat /etc/config/fstab 
config global
      option anon_swap '0'
      option anon_mount '0'
      option auto_swap '0'
      option auto_mount '0'
      option delay_root '3'
      option check_fs '0'

config swap
      option uuid '[...]'
      option enabled '1'

config mount
      option target '/overlay'
      option uuid '[...]'
      option fstype 'ext4'
      option options 'rw,noatime'
      option enabled '1'
      option enabled_fsck '0'

config mount
      option target '/mnt/data'
      option uuid '[...]'
      option fstype 'ext4'
      option options 'rw,noatime'
      option enabled '1'
      option enabled_fsck '0'
```

i.e. `/etc/fstab` is empty. the mount points are recorded in `/etc/config/fstab`.

**Comment by mburlic** [comment]
Yep I was looking at /etc/config/fstab

```
config global
	option anon_swap '0'
	option anon_mount '0'
	option auto_swap '1'
	option auto_mount '1'
	option delay_root '5'
	option check_fs '0'

config mount 'rwm'
	option device '/dev/ubi0_1'
	option target '/rwm'
	option enabled '1'

config mount 'extroot'
	option uuid '...'
	option target '/overlay'
	option enabled '1'
```

**Comment by mburlic** [comment]
OK, had a look at my backup that I created prior to flash. /etc/config/fstab has contents that I posted... Really no idea why...
Flashed again, changed /etc/config/fstab, restored backup, everything fine.

**Comment by attila-lendvai** [comment]
strange, because `/etc/config/fstab` should be included on the extroot filesystem as-is, and it looks like this in the repo:

https://github.com/attila-lendvai/openwrt-auto-extroot/blob/openwrt-23/image-extras/common/etc/config/fstab

this is what you should see after the extroot setup has just finished, and extroot is mounted after a reboot.

**Comment by mburlic** [comment]
Yes that is exactly what is in /etc/config/fstab after extroot setup. IDK how and why different config was in backup... 
I replaced fstab in backup... everything A-OK
