### ISSUE TITLE
TL MR3040 V2

### ISSUE THREAD

**Issue by not-alone** [attila-lendvai/openwrt-auto-extroot#4]
Hi!
In 
$make info | grep 3040
TLMR3040:
        TP-LINK TL-MR3040
i found only TL-MR3040.
Is it means  that TL-MR3040 V2 is not supported by this script?

UPDATE:
After successful compilation there a 2 versions of bins for V1 and V2 hardware separately
Nice!!!
Thx

**Comment by attila-lendvai** [comment]
yep, that's how openwrt does it.
